repos:
  # Pre-commit hooks repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: Automatically removes trailing whitespace.
        stages: [pre-commit]
        exclude: README\.md

      - id: end-of-file-fixer
        name: Ensure file ends with a newline
        description: Ensures that files end with a single newline.
        stages: [pre-commit]

  # Black (code formatter) repository
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Specify the version you want
    hooks:
      - id: black
        name: Black code formatter
        description: Automatically formats Python code to conform to PEP 8.
        stages: [pre-commit]

  # Flake8 (linter) repository from GitHub (if GitLab fails)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Specify the version you want
    hooks:
      - id: flake8
        name: Flake8 linter
        description: Runs flake8 to check for coding style issues.
        stages: [pre-commit]
