repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Replace with the latest version if needed
    hooks:
      - id: black
        args: ["--line-length=88"]  # Optional: Customize line length
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Replace with the latest version if needed
    hooks:
      - id: flake8
        args:
          - --max-line-length=88  # Optional: Align with black's line length
        additional_dependencies:  # Add any required plugins here
          - flake8-bugbear
          - flake8-comprehensions
